[package]
name = "postgres-connect-sample-rs"
version = "0.1.0"
authors = ["4832cl0n"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0.1"
actix-rt = "1.0.0"